# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

language: cpp
dist: bionic
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update

  # Ensure add-apt-repository is installed.
  - sudo apt-get install python-software-properties

  # LLVM
  - sudo sh -c "echo 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main' >> /etc/apt/sources.list"
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

install:
  # Install package dependencies.
  # (Re-run this command a few times to handle handle random failures.)
  -
    for i in {1..5}; do
      if sudo apt-get update && sudo apt-get install -y llvm-$LLVM_VERSION llvm-$LLVM_VERSION-dev clang-$LLVM_VERSION; then
        break;
      fi;
      sleep 1;
    done

  # use the previously installed clang version (since installing one tends to remove another).
  -
    if [[ "${CXX}" == "clang++" ]]; then
      export CXX="clang++-$LLVM_VERSION";
    fi

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_INSTALL_PREFIX=./artifacts/llvm-abi ..
  - make && ctest --output-on-failure
  - make install

env:
  - BUILD_TYPE=Debug LLVM_VERSION="9"
  - BUILD_TYPE=Release LLVM_VERSION="9"

